version: "3.8"

services:
  app:
    container_name: smartbutler
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - "8888:8080"
    depends_on:
      - database
    restart: on-failure
    links:
      - database
      
  database:
    container_name: smartbutler-db
    build:
      context: .
      dockerfile: Dockerfile-db
    hostname: smartbutler-db
    ports:
       - 3307:3306
    environment:
      MYSQL_DATABASE: smartbutler
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 1111
    